const menu = [
{
    id: 1,
    title: 'Passwang Pass',
    category: 'Mountain',
    price: 1100,
    img:'img/pass.jpg',
    desc: `Passwang Pass is a scenic mountain pass in the Jura Mountains, Switzerland, connecting Laufen and Balsthal. It offers lush landscapes, recreational activities, and historical significance.`,
},
{
    id: 2,
    title: 'Mürren',
    category: 'Mountain',
    price: 1200,
    img:'img/murren.jpg',
    desc: `Mürren is a picturesque alpine village in Switzerland, nestled in the Bernese Oberland. Surrounded by majestic mountains, it offers stunning views, skiing, hiking, and a car-free environment, making it an idyllic destination for nature enthusiasts and adventure seekers.`,
},
{
    id: 3,
    title: 'Zürich',
    category: 'City',
    price: 1300,
    img:'img/zurich.jpg',
    desc: `Zürich is Switzerland's largest city, known for its thriving economy, cultural attractions, and picturesque location on Lake Zürich. It offers a blend of modernity and history, with vibrant neighborhoods, a bustling city center, and a wealth of museums, galleries, and restaurants.`,
},
{
    id: 4,
    title: 'Wengen',
    category: 'Village',
    price: 1400,
    img:'img/wengen.jpg',
    desc: `Wengen is a charming village in the Swiss Alps, situated at the foot of the Jungfrau mountain. It is a popular destination for outdoor enthusiasts, offering stunning alpine scenery, hiking and skiing opportunities, and a peaceful, car-free atmosphere.`,
},
{
    id: 5,
    title: 'Oeschinen Lake',
    category: 'Lake',
    price: 1500,
    img:'img/oeschinen.jpg',
    desc: `Oeschinen Lake is a pristine mountain lake located in the Bernese Oberland region of Switzerland. Surrounded by majestic peaks and lush greenery, it offers hiking trails, fishing, boating, and breathtaking views that attract nature lovers and outdoor enthusiasts.`,
},
{
    id: 6,
    title: 'Furka Pass',
    category: 'Mountain',
    price: 1600,
    img:'img/furka.jpg',
    desc: `Furka Pass is a renowned mountain pass in the Swiss Alps. Connecting the cantons of Uri and Valais, it offers stunning alpine landscapes, hairpin bends, and panoramic views, making it a popular destination for scenic drives, motorcyclists, and nature enthusiasts.`,
},
{
    id: 7,
    title: 'Oberhofen Castle',
    category: 'Castle',
    price: 1700,
    img:'img/castle.jpg',
    desc: `Oberhofen Castle is a picturesque lakeside castle located on the shores of Lake Thun in Switzerland. With its medieval origins and beautiful gardens, it attracts visitors with its rich history, architectural charm, and stunning views of the surrounding mountains and lake.`,
},
{
    id: 8,
    title: 'Bunderspitz',
    category: 'Mountain',
    price: 1800,
    img:'img/bunder.jpg',
    desc: `Bunderspitz is a prominent mountain peak in the Bernese Alps of Switzerland. Standing at an elevation of 2,197 meters, it offers breathtaking panoramic views, challenging hiking trails, and is a popular destination for outdoor enthusiasts seeking alpine adventures and natural beauty.`,
},
{
    id: 9,
    title: 'Rotenboden',
    category: 'Mountain',
    price: 1900,
    img:'img/zermatt.jpg',
    desc: `Rotenboden is a scenic alpine plateau located in the Swiss Alps. Situated at an elevation of 2,815 meters, it offers stunning views of the surrounding mountains and serves as a starting point for hiking, skiing, and mountaineering activities in the region.`,
},
{
    id: 10,
    title: 'Bryggen',
    category: 'Village',
    price: 2000,
    img:'img/bryggen.jpg',
    desc: `Bryggen is a historic wharf in Bergen, Norway. It consists of colorful wooden buildings that date back to the 14th century. It is a UNESCO World Heritage site and a popular tourist destination known for its rich cultural heritage and picturesque waterfront.`,
},
{
    id: 11,
    title: 'Steinsdalsfossen',
    category: 'Waterfall',
    price: 2100,
    img:'img/steinsdalsfossen.jpg',
    desc: `Steinsdalsfossen is a stunning waterfall located near Norheimsund in Hordaland, Norway. It is known for its unique feature that allows visitors to walk behind the cascading water curtain and enjoy breathtaking views of the surrounding landscape.`,
},
{
    id: 12,
    title: 'Hamnøy',
    category: 'Village',
    price: 2100,
    img:'img/hamnoy.jpg',
    desc: `Hamnøy is a picturesque fishing village in the Lofoten Islands, Norway. Surrounded by majestic mountains and stunning fjords, it offers breathtaking scenery and is a popular destination for photographers, outdoor enthusiasts, and those seeking a peaceful retreat.`,
},
]
export default menu
